### Generate Account Key (Random)
PUT {{protocol}}{{host}}{{port}}/account/key
Content-Type: application/json

{
  "pk": 1,
  "random": true,
  "length": 1023,
  "lowers": true,
  "uppers": true,
  "numbers": true,
  "specials": true
}

### Get Account Key
GET {{protocol}}{{host}}{{port}}/account/key?account=1

### Replace Account Key (User-Provided Plain Text)
PUT {{protocol}}{{host}}{{port}}/account/key
Content-Type: application/json

{
  "pk": 1,
  "key": "hunter2"
}