### Missing JSON fields
POST {{protocol}}{{host}}{{port}}/login
Content-Type: application/json

{}

### Invalid UID
POST {{protocol}}{{host}}{{port}}/login
Content-Type: application/json

{
  "username": 9999,
  "key": ""
}

### Valid UID, invalid password
POST {{protocol}}{{host}}{{port}}/login
Content-Type: application/json

{
  "username": 1,
  "key": ""
}

### Valid UID and password
POST {{protocol}}{{host}}{{port}}/login
Content-Type: application/json

{
  "username": "jsmith1",
  "key": "cornucopia"
}
