### Create New User
POST {{protocol}}{{host}}{{port}}/user
Content-Type: application/json

{
  "pk": -1,
  "username": "jsmith1",
  "firstName": "John",
  "lastName": "Smith",
  "keyHash": "cornucopia"
}

### Get List of All Users
GET {{protocol}}{{host}}{{port}}/users

### Get Single User (1)
GET {{protocol}}{{host}}{{port}}/user?pk=1

### Get Single User (jsmith1)
GET {{protocol}}{{host}}{{port}}/user?username=jsmith1

### Get Single User, pass both params
GET {{protocol}}{{host}}{{port}}/user?username=jsmith1&pk=2

### Update Existing User
PATCH {{protocol}}{{host}}{{port}}/user
Content-Type: application/json

{
  "pk": 1,
  "firstName": "Jane",
  "lastName": "Doe"
}

### Delete User 2
DELETE {{protocol}}{{host}}{{port}}/user
Content-Type: application/json

{
  "pk": 2
}