### Valid data
POST {{protocol}}{{host}}:{{port}}/account-key
Content-Type: application/json

{
  "pk": 2
}

### Invalid data (account with this pk doesn't exist)
POST {{protocol}}{{host}}:{{port}}/account-key
Content-Type: application/json

{
  "pk": 9999
}

### Missing field
POST {{protocol}}{{host}}:{{port}}/account-key
Content-Type: application/json

{}
